[package]
name = "repl"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = { workspace = true, features = ["fancy"] }
rustyline = { version = "11.0.0", features = ["derive"] }
execution = { path = "../execution" }
parser = { path = "../parser" }
tabled = "0.10.0"
